version: "2.2"

networks:
  demo-connection:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/usr/src
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=database
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=""
    networks:
      - demo-connection
    entrypoint: ["./.docker/init.sh"]
  database:
    restart: always
    image: postgres
    volumes:
      - ./.docker/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready" ,"-h", "localhost", "-p", "5432"]
      interval: 20s
      timeout: 20s
      retries: 3
    networks:
      - demo-connection